
# Site settings
title: "Richard Myer | Bronze Sculptor"
email: "team@variantstudios.com"
description: "Richard Myer a bronze sculptor located in Glendora, California."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.richardmyer.com" # the base hostname & protocol for your site
#timezone: America/Denver - Don't set for CloudCannon...for reasons.
uploads_dir: "/assets/images/"
version: "3.0.3" # the version of jekyll
author.name: "Variant Studios"
author.email: "team@variantstudios.com"

# Gems for plugins
gems:
  - jekyll-paginate # Needed to add paginate on Jekyll ver 3+
  - jekyll-sitemap # Simple jekyll plugin that creates a sitemap.xml file and you can exclude files by adding 'sitemap:false' to the frontmatter of any file(s).

# Permalinks
permalink: pretty

#Collections
collections:
  sculptures:
    output: true
    permalink: '/sculptures/:title/'
  events:
    output: false

defaults:
  -
    scope:
      type: sculptures
    values:
      layout: sculpture
    scope:
      type: events
    values:
      title:
      dates:
      location:
      weight:

sculpture_categories:
    - 'Globes'
    - 'Monuments'
    - 'Western'

# typekit - Because we all need nice type faces.
typekit: rrr6qqb

# Google Analytics - What site isn't using it?!
google_analytics_tracking_id: 'UA-1299264-55'

exclude: ["vendor","node_modules","package.json","Gemfile","gulpfile.js","*.scss"]
